export const exposedHeaders = [
  "Content-Length",
  "Content-Range",
  "Content-Type",
  "ETag",
  "Last-Modified",
  "Link",
  "Location",
  "Refresh",
  "Retry-After",
  // 'Server',
  "Set-Cookie",
  "Vary",
  "WWW-Authenticate",
];
